"""added admins and servers

Revision ID: 091b98d952b2
Revises: 5b59a517ca1d
Create Date: 2024-09-21 15:01:57.619781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091b98d952b2'
down_revision: Union[str, None] = '5b59a517ca1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_tg_id'), 'admins', ['tg_id'], unique=True)
    op.create_table('servers',
    sa.Column('server_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('cert_sha256', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('api_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_index(op.f('ix_admins_tg_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
