"""Remove foreign keys

Revision ID: 535fca0d5266
Revises: 
Create Date: 2024-09-15 23:57:20.774987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535fca0d5266'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logs_user_id_fkey', 'logs', type_='foreignkey')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_vpn_key_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_service_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('transactions_service_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('transactions_service_id_fkey', 'transactions', 'services', ['service_id'], ['service_id'])
    op.create_foreign_key('subscriptions_service_id_fkey', 'subscriptions', 'services', ['service_id'], ['service_id'])
    op.create_foreign_key('subscriptions_vpn_key_id_fkey', 'subscriptions', 'vpn_keys', ['vpn_key_id'], ['vpn_key_id'])
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('logs_user_id_fkey', 'logs', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
