"""update models

Revision ID: 53ac43e6d988
Revises: 7e783681cd7f
Create Date: 2024-09-26 14:41:06.335454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ac43e6d988'
down_revision: Union[str, None] = '7e783681cd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_keys', sa.Column('server_id', sa.String(), nullable=False))
    op.alter_column('vpn_keys', 'outline_key_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('vpn_keys', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_keys', sa.Column('is_blocked', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('vpn_keys', 'outline_key_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('vpn_keys', 'server_id')
    # ### end Alembic commands ###
