"""update models vpn and subs

Revision ID: 6489f386f08d
Revises: a8fa45556031
Create Date: 2024-09-27 20:17:18.115631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6489f386f08d'
down_revision: Union[str, None] = 'a8fa45556031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'status')
    # ### end Alembic commands ###
