"""migrations02-10-2024-20-54

Revision ID: a0454651b082
Revises: 77853ea816de
Create Date: 2024-10-02 20:54:53.732434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0454651b082'
down_revision: Union[str, None] = '77853ea816de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_tg_id', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('admin_id', name='admins_pkey')
    )
    op.create_index('ix_admins_tg_id', 'admins', ['tg_id'], unique=True)
    # ### end Alembic commands ###
