"""update

Revision ID: a22a4a024793
Revises: 
Create Date: 2024-09-20 10:17:41.510655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a22a4a024793'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_tg_id', table_name='admins')
    op.drop_table('admins')
    op.alter_column('logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs', 'details',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('logs', 'details',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('admins',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='admins_pkey')
    )
    op.create_index('ix_admins_tg_id', 'admins', ['tg_id'], unique=True)
    # ### end Alembic commands ###
