"""update models vpn and subs

Revision ID: a8fa45556031
Revises: 53ac43e6d988
Create Date: 2024-09-27 20:14:47.410796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fa45556031'
down_revision: Union[str, None] = '53ac43e6d988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_keys', sa.Column('is_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_keys', 'is_limit')
    # ### end Alembic commands ###
